export PYTHONPATH=$HOME/work/rnawl/src/:$PYTHONPATH
export PATH=$HOME/miniconda2/bin:$PATH

~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple setproctitle
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple bson
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple pymongo
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple boto
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple grpcio
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple googlt
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple googl
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple protobuf==3.15.8

~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple web.py==0.51
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple psutil
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple rpy2==2.7.4
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple pandas==0.23.3
~/miniconda2/bin/pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple gevent


~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple argh==0.26.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple argparse==1.4.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple asn1crypto==0.24.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple backports_abc==0.5

~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple bagit==1.8.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple beautifulsoup4==4.9.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple biome==0.1.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple boto==2.49.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple boto3==1.9.11
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple botocore==1.12.11
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple bs4==0.0.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple CacheControl==0.11.7
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple certifi==2020.4.5.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cffi==1.11.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple chardet==3.0.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple click==7.1.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple coloredlogs==15.0.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple colour==0.1.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple configparser==4.0.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple coverage==5.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple CPAT==1.2.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cryptography==2.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cssselect==1.0.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cssselect2==0.2.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cutadapt==1.14
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cwltool==1.0.20191225192155
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple cycler==0.10.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple Cython==0.29.22
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple dask==1.2.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple decorator==4.0.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple docutils==0.14
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple falcon_kit==1.2.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple fastcluster==1.1.24
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple fitz==0.0.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple flake8==2.6.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple funcsigs==1.0.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple futures==3.2.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple graphviz==0.10.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple grpcio==1.34.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple h5py==2.7.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple html5lib==1.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple humanfriendly==10.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple idna==2.9
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ijson==3.1.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ipaddress==1.0.16
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ipykernel==4.10.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ipython==4.0.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ipython_genutils==0.1.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple isodate==0.6.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple Jinja2==2.11.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple jmespath==0.9.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple jsonpath==0.82                                                                                          [54/1950]
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple jupyter_client==5.3.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple jupyter_console==5.2.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple jupyter_core==4.6.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple kiwisolver==1.0.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple lockfile==0.12.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple lxml==4.5.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple matplotlib==2.2.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple mccabe==0.5.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple memory_profiler==0.57.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple MiniMock==1.2.8
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple mistune==0.8.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple monotonic==1.6
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple mypy_extensions==0.4.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple natsort==3.5.6
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple netaddr==0.7.18
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple networkx==1.11
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple nipype==1.3.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple nose==1.3.7
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple numexpr==2.6.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple numpy==1.13.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple packaging==20.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pathlib2==2.3.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple path.py==8.1.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple patsy==0.5.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple Pillow==4.0.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pip==20.3.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple prettytable==1.0.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple progressbar2==3.37.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple prompt_toolkit==1.0.18
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple protobuf==3.15.8                                                                                        [24/1950]
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple prov==1.5.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pyasn1==0.1.9
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pycodestyle==2.0.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pydot==1.4.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pyecharts==1.5.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pyflakes==1.2.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple Pygments==2.5.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pymemcache==2.1.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pymongo==3.11.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple PyMuPDF==1.16.18
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pyparsing==2.1.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pypeflow==2.0.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pysam==0.13
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple python_dateutil==2.5.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple python_memcached==1.59
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple python_utils==2.3.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple pytz==2016.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple rdflib==4.2.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple rdflib_jsonld==0.4.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple reportlab==3.5.9
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple requests==2.23.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple requests_toolbelt==0.7.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple RSeQC==2.6.4
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ruamel.ordereddict==0.4.15
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ruamel.yaml==0.16.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple ruamel.yaml.clib==0.2.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple s3transfer==0.1.13
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple schema_salad==4.5.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple scikit_learn==0.19.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple scipy==1.0.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple setuptools==40.4.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple shellescape==3.4.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple singledispatch==3.4.0.3
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple six==1.10.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple soupsieve==1.9.6
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple statsmodels==0.8.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple svgwrite==1.3.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple tinycss2==0.6.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple tornado==5.1.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple tqdm==4.46.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple traitlets==4.1.0b1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple typing==3.10.0.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple typing_extensions==3.10.0.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple Unipath==1.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple urllib3==1.23
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple virtualenv==15.1.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple wcwidth==0.2.5
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple webencodings==0.5.1
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple wheel==0.36.2
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple XlsxWriter==1.2.8
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple xlwt==1.3.0
~/miniconda2/bin/pip install  -i  https://pypi.tuna.tsinghua.edu.cn/simple xopen==0.2.1


conda install r-base=3.5.1
conda install rpy2
install.packages("fastcluster")
