# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='configserver',
  syntax='proto3',
  serialized_options=_b('Z\007.;wfmpb'),
  serialized_pb=_b('\n\x0c\x63onfig.proto\x12\x0c\x63onfigserver\"\x1b\n\x0bProjectType\x12\x0c\n\x04type\x18\x01 \x01(\t\"\x1b\n\x0cRegionBucket\x12\x0b\n\x03url\x18\x01 \x01(\t\",\n\nBucketInfo\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\"`\n\nRgwAccount\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08issecure\x18\x03 \x01(\x08\x12\x11\n\taccesskey\x18\x04 \x01(\t\x12\x11\n\tsecretkey\x18\x05 \x01(\t\"j\n\x07WebAuth\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06\x63lient\x18\x02 \x01(\t\x12\x0f\n\x07\x62indsid\x18\x03 \x01(\t\x12\x13\n\x0binterfaceid\x18\x04 \x01(\x05\x12\x0f\n\x07\x65nvname\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\":\n\x06\x44\x42Type\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\tprojectid\x18\x03 \x01(\t\"M\n\x0bMongoDBInfo\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x62name\x18\x02 \x01(\t\x12\x0e\n\x06refuri\x18\x03 \x01(\t\x12\x11\n\trefdbname\x18\x04 \x01(\t\"\x14\n\x04Path\x12\x0c\n\x04path\x18\x01 \x01(\t2\xec\x02\n\x0c\x43onfigServer\x12K\n\x10GetProjectBucket\x12\x19.configserver.ProjectType\x1a\x1a.configserver.RegionBucket\"\x00\x12?\n\nGetMongoDB\x12\x14.configserver.DBType\x1a\x19.configserver.MongoDBInfo\"\x00\x12\x45\n\rGetRgwAccount\x12\x18.configserver.BucketInfo\x1a\x18.configserver.RgwAccount\"\x00\x12\x45\n\x11GetBucketFromPath\x12\x12.configserver.Path\x1a\x1a.configserver.RegionBucket\"\x00\x12@\n\nGetWebAuth\x12\x19.configserver.ProjectType\x1a\x15.configserver.WebAuth\"\x00\x42\tZ\x07.;wfmpbb\x06proto3')
)




_PROJECTTYPE = _descriptor.Descriptor(
  name='ProjectType',
  full_name='configserver.ProjectType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='configserver.ProjectType.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)


_REGIONBUCKET = _descriptor.Descriptor(
  name='RegionBucket',
  full_name='configserver.RegionBucket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='configserver.RegionBucket.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=86,
)


_BUCKETINFO = _descriptor.Descriptor(
  name='BucketInfo',
  full_name='configserver.BucketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='configserver.BucketInfo.region', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='configserver.BucketInfo.bucket', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=132,
)


_RGWACCOUNT = _descriptor.Descriptor(
  name='RgwAccount',
  full_name='configserver.RgwAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='configserver.RgwAccount.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='configserver.RgwAccount.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issecure', full_name='configserver.RgwAccount.issecure', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accesskey', full_name='configserver.RgwAccount.accesskey', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secretkey', full_name='configserver.RgwAccount.secretkey', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=230,
)


_WEBAUTH = _descriptor.Descriptor(
  name='WebAuth',
  full_name='configserver.WebAuth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='configserver.WebAuth.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='configserver.WebAuth.client', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bindsid', full_name='configserver.WebAuth.bindsid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interfaceid', full_name='configserver.WebAuth.interfaceid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='envname', full_name='configserver.WebAuth.envname', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='configserver.WebAuth.url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=338,
)


_DBTYPE = _descriptor.Descriptor(
  name='DBType',
  full_name='configserver.DBType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='configserver.DBType.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='configserver.DBType.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projectid', full_name='configserver.DBType.projectid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=398,
)


_MONGODBINFO = _descriptor.Descriptor(
  name='MongoDBInfo',
  full_name='configserver.MongoDBInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='configserver.MongoDBInfo.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbname', full_name='configserver.MongoDBInfo.dbname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refuri', full_name='configserver.MongoDBInfo.refuri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refdbname', full_name='configserver.MongoDBInfo.refdbname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=477,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='configserver.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='configserver.Path.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=499,
)

DESCRIPTOR.message_types_by_name['ProjectType'] = _PROJECTTYPE
DESCRIPTOR.message_types_by_name['RegionBucket'] = _REGIONBUCKET
DESCRIPTOR.message_types_by_name['BucketInfo'] = _BUCKETINFO
DESCRIPTOR.message_types_by_name['RgwAccount'] = _RGWACCOUNT
DESCRIPTOR.message_types_by_name['WebAuth'] = _WEBAUTH
DESCRIPTOR.message_types_by_name['DBType'] = _DBTYPE
DESCRIPTOR.message_types_by_name['MongoDBInfo'] = _MONGODBINFO
DESCRIPTOR.message_types_by_name['Path'] = _PATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProjectType = _reflection.GeneratedProtocolMessageType('ProjectType', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTTYPE,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.ProjectType)
  })
_sym_db.RegisterMessage(ProjectType)

RegionBucket = _reflection.GeneratedProtocolMessageType('RegionBucket', (_message.Message,), {
  'DESCRIPTOR' : _REGIONBUCKET,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.RegionBucket)
  })
_sym_db.RegisterMessage(RegionBucket)

BucketInfo = _reflection.GeneratedProtocolMessageType('BucketInfo', (_message.Message,), {
  'DESCRIPTOR' : _BUCKETINFO,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.BucketInfo)
  })
_sym_db.RegisterMessage(BucketInfo)

RgwAccount = _reflection.GeneratedProtocolMessageType('RgwAccount', (_message.Message,), {
  'DESCRIPTOR' : _RGWACCOUNT,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.RgwAccount)
  })
_sym_db.RegisterMessage(RgwAccount)

WebAuth = _reflection.GeneratedProtocolMessageType('WebAuth', (_message.Message,), {
  'DESCRIPTOR' : _WEBAUTH,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.WebAuth)
  })
_sym_db.RegisterMessage(WebAuth)

DBType = _reflection.GeneratedProtocolMessageType('DBType', (_message.Message,), {
  'DESCRIPTOR' : _DBTYPE,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.DBType)
  })
_sym_db.RegisterMessage(DBType)

MongoDBInfo = _reflection.GeneratedProtocolMessageType('MongoDBInfo', (_message.Message,), {
  'DESCRIPTOR' : _MONGODBINFO,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.MongoDBInfo)
  })
_sym_db.RegisterMessage(MongoDBInfo)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configserver.Path)
  })
_sym_db.RegisterMessage(Path)


DESCRIPTOR._options = None

_CONFIGSERVER = _descriptor.ServiceDescriptor(
  name='ConfigServer',
  full_name='configserver.ConfigServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=502,
  serialized_end=866,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProjectBucket',
    full_name='configserver.ConfigServer.GetProjectBucket',
    index=0,
    containing_service=None,
    input_type=_PROJECTTYPE,
    output_type=_REGIONBUCKET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMongoDB',
    full_name='configserver.ConfigServer.GetMongoDB',
    index=1,
    containing_service=None,
    input_type=_DBTYPE,
    output_type=_MONGODBINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRgwAccount',
    full_name='configserver.ConfigServer.GetRgwAccount',
    index=2,
    containing_service=None,
    input_type=_BUCKETINFO,
    output_type=_RGWACCOUNT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBucketFromPath',
    full_name='configserver.ConfigServer.GetBucketFromPath',
    index=3,
    containing_service=None,
    input_type=_PATH,
    output_type=_REGIONBUCKET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetWebAuth',
    full_name='configserver.ConfigServer.GetWebAuth',
    index=4,
    containing_service=None,
    input_type=_PROJECTTYPE,
    output_type=_WEBAUTH,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGSERVER)

DESCRIPTOR.services_by_name['ConfigServer'] = _CONFIGSERVER

# @@protoc_insertion_point(module_scope)
