# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import config_pb2 as config__pb2


class ConfigServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProjectBucket = channel.unary_unary(
        '/configserver.ConfigServer/GetProjectBucket',
        request_serializer=config__pb2.ProjectType.SerializeToString,
        response_deserializer=config__pb2.RegionBucket.FromString,
        )
    self.GetMongoDB = channel.unary_unary(
        '/configserver.ConfigServer/GetMongoDB',
        request_serializer=config__pb2.DBType.SerializeToString,
        response_deserializer=config__pb2.MongoDBInfo.FromString,
        )
    self.GetRgwAccount = channel.unary_unary(
        '/configserver.ConfigServer/GetRgwAccount',
        request_serializer=config__pb2.BucketInfo.SerializeToString,
        response_deserializer=config__pb2.RgwAccount.FromString,
        )
    self.GetBucketFromPath = channel.unary_unary(
        '/configserver.ConfigServer/GetBucketFromPath',
        request_serializer=config__pb2.Path.SerializeToString,
        response_deserializer=config__pb2.RegionBucket.FromString,
        )
    self.GetWebAuth = channel.unary_unary(
        '/configserver.ConfigServer/GetWebAuth',
        request_serializer=config__pb2.ProjectType.SerializeToString,
        response_deserializer=config__pb2.WebAuth.FromString,
        )


class ConfigServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProjectBucket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMongoDB(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRgwAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBucketFromPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWebAuth(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConfigServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProjectBucket': grpc.unary_unary_rpc_method_handler(
          servicer.GetProjectBucket,
          request_deserializer=config__pb2.ProjectType.FromString,
          response_serializer=config__pb2.RegionBucket.SerializeToString,
      ),
      'GetMongoDB': grpc.unary_unary_rpc_method_handler(
          servicer.GetMongoDB,
          request_deserializer=config__pb2.DBType.FromString,
          response_serializer=config__pb2.MongoDBInfo.SerializeToString,
      ),
      'GetRgwAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetRgwAccount,
          request_deserializer=config__pb2.BucketInfo.FromString,
          response_serializer=config__pb2.RgwAccount.SerializeToString,
      ),
      'GetBucketFromPath': grpc.unary_unary_rpc_method_handler(
          servicer.GetBucketFromPath,
          request_deserializer=config__pb2.Path.FromString,
          response_serializer=config__pb2.RegionBucket.SerializeToString,
      ),
      'GetWebAuth': grpc.unary_unary_rpc_method_handler(
          servicer.GetWebAuth,
          request_deserializer=config__pb2.ProjectType.FromString,
          response_serializer=config__pb2.WebAuth.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'configserver.ConfigServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
