# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filetrans.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_pb2 as public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='filetrans.proto',
  package='filetrans',
  syntax='proto3',
  serialized_options=_b('Z\007.;wfmpb'),
  serialized_pb=_b('\n\x0f\x66iletrans.proto\x12\tfiletrans\x1a\x0cpublic.proto\"\xa8\x01\n\tFileTrans\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0f\n\x07tool_id\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x11\n\tprocessid\x18\x04 \x01(\x05\x12\x0e\n\x06upload\x18\x05 \x01(\x08\x12\x10\n\x08\x66rompath\x18\x06 \x01(\t\x12\x0e\n\x06topath\x18\x07 \x01(\t\x12\x10\n\x08\x62\x61sepath\x18\x08 \x01(\t\x12\x10\n\x08usecache\x18\t \x01(\x08\"\xd5\x01\n\x08Progress\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x12\n\ntotal_size\x18\x02 \x01(\x03\x12\x14\n\x0ctrans_number\x18\x03 \x01(\x05\x12\x12\n\ntrans_size\x18\x04 \x01(\x03\x12\x12\n\ncache_size\x18\x05 \x01(\x03\x12\x14\n\x0c\x63\x61\x63he_number\x18\x06 \x01(\x05\x12\x12\n\nerror_size\x18\x07 \x01(\x03\x12\x14\n\x0c\x65rror_number\x18\x08 \x01(\x05\x12\x0b\n\x03\x65nd\x18\t \x01(\x08\x12\x0c\n\x04info\x18\n \x01(\t\x12\r\n\x05speed\x18\x0b \x01(\x03\"W\n\x0eWorkflowOrTool\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0f\n\x07tool_id\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x11\n\tprocessid\x18\x04 \x01(\x05\x32\xb7\x01\n\x0f\x46ileTransServer\x12\x30\n\x05Trans\x12\x14.filetrans.FileTrans\x1a\x0f.public.Success\"\x00\x12:\n\x04Wait\x12\x19.filetrans.WorkflowOrTool\x1a\x13.filetrans.Progress\"\x00\x30\x01\x12\x36\n\tTransFile\x12\x14.filetrans.FileTrans\x1a\x0f.public.Success\"\x00(\x01\x42\tZ\x07.;wfmpbb\x06proto3')
  ,
  dependencies=[public__pb2.DESCRIPTOR,])




_FILETRANS = _descriptor.Descriptor(
  name='FileTrans',
  full_name='filetrans.FileTrans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='filetrans.FileTrans.workflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tool_id', full_name='filetrans.FileTrans.tool_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='filetrans.FileTrans.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processid', full_name='filetrans.FileTrans.processid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upload', full_name='filetrans.FileTrans.upload', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frompath', full_name='filetrans.FileTrans.frompath', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topath', full_name='filetrans.FileTrans.topath', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basepath', full_name='filetrans.FileTrans.basepath', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usecache', full_name='filetrans.FileTrans.usecache', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=213,
)


_PROGRESS = _descriptor.Descriptor(
  name='Progress',
  full_name='filetrans.Progress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='filetrans.Progress.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_size', full_name='filetrans.Progress.total_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trans_number', full_name='filetrans.Progress.trans_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trans_size', full_name='filetrans.Progress.trans_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache_size', full_name='filetrans.Progress.cache_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache_number', full_name='filetrans.Progress.cache_number', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_size', full_name='filetrans.Progress.error_size', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_number', full_name='filetrans.Progress.error_number', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='filetrans.Progress.end', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='filetrans.Progress.info', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='filetrans.Progress.speed', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=429,
)


_WORKFLOWORTOOL = _descriptor.Descriptor(
  name='WorkflowOrTool',
  full_name='filetrans.WorkflowOrTool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='filetrans.WorkflowOrTool.workflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tool_id', full_name='filetrans.WorkflowOrTool.tool_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='filetrans.WorkflowOrTool.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processid', full_name='filetrans.WorkflowOrTool.processid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=518,
)

DESCRIPTOR.message_types_by_name['FileTrans'] = _FILETRANS
DESCRIPTOR.message_types_by_name['Progress'] = _PROGRESS
DESCRIPTOR.message_types_by_name['WorkflowOrTool'] = _WORKFLOWORTOOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileTrans = _reflection.GeneratedProtocolMessageType('FileTrans', (_message.Message,), {
  'DESCRIPTOR' : _FILETRANS,
  '__module__' : 'filetrans_pb2'
  # @@protoc_insertion_point(class_scope:filetrans.FileTrans)
  })
_sym_db.RegisterMessage(FileTrans)

Progress = _reflection.GeneratedProtocolMessageType('Progress', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESS,
  '__module__' : 'filetrans_pb2'
  # @@protoc_insertion_point(class_scope:filetrans.Progress)
  })
_sym_db.RegisterMessage(Progress)

WorkflowOrTool = _reflection.GeneratedProtocolMessageType('WorkflowOrTool', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWORTOOL,
  '__module__' : 'filetrans_pb2'
  # @@protoc_insertion_point(class_scope:filetrans.WorkflowOrTool)
  })
_sym_db.RegisterMessage(WorkflowOrTool)


DESCRIPTOR._options = None

_FILETRANSSERVER = _descriptor.ServiceDescriptor(
  name='FileTransServer',
  full_name='filetrans.FileTransServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=521,
  serialized_end=704,
  methods=[
  _descriptor.MethodDescriptor(
    name='Trans',
    full_name='filetrans.FileTransServer.Trans',
    index=0,
    containing_service=None,
    input_type=_FILETRANS,
    output_type=public__pb2._SUCCESS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Wait',
    full_name='filetrans.FileTransServer.Wait',
    index=1,
    containing_service=None,
    input_type=_WORKFLOWORTOOL,
    output_type=_PROGRESS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransFile',
    full_name='filetrans.FileTransServer.TransFile',
    index=2,
    containing_service=None,
    input_type=_FILETRANS,
    output_type=public__pb2._SUCCESS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILETRANSSERVER)

DESCRIPTOR.services_by_name['FileTransServer'] = _FILETRANSSERVER

# @@protoc_insertion_point(module_scope)
