# -*- coding: utf-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import public_pb2 as public__pb2
import webapi_pb2 as webapi__pb2


class WebApiStub(object):
  """Wfm与web端接口通信，接收工作流任务,接收control cmd
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Submit = channel.unary_unary(
        '/webapi.WebApi/Submit',
        request_serializer=webapi__pb2.Task.SerializeToString,
        response_deserializer=public__pb2.Success.FromString,
        )
    self.Control = channel.unary_unary(
        '/webapi.WebApi/Control',
        request_serializer=webapi__pb2.Command.SerializeToString,
        response_deserializer=public__pb2.Success.FromString,
        )
    self.S3delete = channel.unary_unary(
        '/webapi.WebApi/S3delete',
        request_serializer=webapi__pb2.Proinfo.SerializeToString,
        response_deserializer=public__pb2.Success.FromString,
        )


class WebApiServicer(object):
  """Wfm与web端接口通信，接收工作流任务,接收control cmd
  """

  def Submit(self, request, context):
    """发送任务
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Control(self, request, context):
    """Control操作
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def S3delete(self, request, context):
    """文件删除
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WebApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Submit': grpc.unary_unary_rpc_method_handler(
          servicer.Submit,
          request_deserializer=webapi__pb2.Task.FromString,
          response_serializer=public__pb2.Success.SerializeToString,
      ),
      'Control': grpc.unary_unary_rpc_method_handler(
          servicer.Control,
          request_deserializer=webapi__pb2.Command.FromString,
          response_serializer=public__pb2.Success.SerializeToString,
      ),
      'S3delete': grpc.unary_unary_rpc_method_handler(
          servicer.S3delete,
          request_deserializer=webapi__pb2.Proinfo.FromString,
          response_serializer=public__pb2.Success.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'webapi.WebApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
