# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_pb2 as public__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='webapi.proto',
  package='webapi',
  syntax='proto3',
  serialized_options=_b('Z\007.;wfmpb'),
  serialized_pb=_b('\n\x0cwebapi.proto\x12\x06webapi\x1a\x0cpublic.proto\"A\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x63lient\x18\x02 \x01(\t\x12\x0c\n\x04json\x18\x03 \x01(\t\x12\x0f\n\x07instant\x18\x04 \x01(\x08\"a\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x03msg\x18\x02 \x01(\x0e\x32\x13.webapi.Command.Cmd\"(\n\x03\x43md\x12\x08\n\x04stop\x10\x00\x12\t\n\x05pause\x10\x01\x12\x0c\n\x08\x63ontinue\x10\x02\">\n\x07Proinfo\x12\x11\n\tprojectid\x18\x01 \x01(\t\x12\x0e\n\x06taskid\x18\x02 \x01(\t\x12\x10\n\x08uniqueid\x18\x03 \x01(\t2\x92\x01\n\x06WebApi\x12)\n\x06Submit\x12\x0c.webapi.Task\x1a\x0f.public.Success\"\x00\x12-\n\x07\x43ontrol\x12\x0f.webapi.Command\x1a\x0f.public.Success\"\x00\x12.\n\x08S3delete\x12\x0f.webapi.Proinfo\x1a\x0f.public.Success\"\x00\x42\tZ\x07.;wfmpbb\x06proto3')
  ,
  dependencies=[public__pb2.DESCRIPTOR,])



_COMMAND_CMD = _descriptor.EnumDescriptor(
  name='Cmd',
  full_name='webapi.Command.Cmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='stop', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pause', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='continue', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_CMD)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='webapi.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='webapi.Task.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='webapi.Task.client', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='json', full_name='webapi.Task.json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instant', full_name='webapi.Task.instant', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=103,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='webapi.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='webapi.Command.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='webapi.Command.msg', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_CMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=202,
)


_PROINFO = _descriptor.Descriptor(
  name='Proinfo',
  full_name='webapi.Proinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectid', full_name='webapi.Proinfo.projectid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taskid', full_name='webapi.Proinfo.taskid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uniqueid', full_name='webapi.Proinfo.uniqueid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=266,
)

_COMMAND.fields_by_name['msg'].enum_type = _COMMAND_CMD
_COMMAND_CMD.containing_type = _COMMAND
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Proinfo'] = _PROINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'webapi_pb2'
  # @@protoc_insertion_point(class_scope:webapi.Task)
  })
_sym_db.RegisterMessage(Task)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'webapi_pb2'
  # @@protoc_insertion_point(class_scope:webapi.Command)
  })
_sym_db.RegisterMessage(Command)

Proinfo = _reflection.GeneratedProtocolMessageType('Proinfo', (_message.Message,), {
  'DESCRIPTOR' : _PROINFO,
  '__module__' : 'webapi_pb2'
  # @@protoc_insertion_point(class_scope:webapi.Proinfo)
  })
_sym_db.RegisterMessage(Proinfo)


DESCRIPTOR._options = None

_WEBAPI = _descriptor.ServiceDescriptor(
  name='WebApi',
  full_name='webapi.WebApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=269,
  serialized_end=415,
  methods=[
  _descriptor.MethodDescriptor(
    name='Submit',
    full_name='webapi.WebApi.Submit',
    index=0,
    containing_service=None,
    input_type=_TASK,
    output_type=public__pb2._SUCCESS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Control',
    full_name='webapi.WebApi.Control',
    index=1,
    containing_service=None,
    input_type=_COMMAND,
    output_type=public__pb2._SUCCESS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='S3delete',
    full_name='webapi.WebApi.S3delete',
    index=2,
    containing_service=None,
    input_type=_PROINFO,
    output_type=public__pb2._SUCCESS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBAPI)

DESCRIPTOR.services_by_name['WebApi'] = _WEBAPI

# @@protoc_insertion_point(module_scope)
