# -*- coding: utf-8 -*-
# __author__ = 'liubinxu'

import re
import os
import sys

class RefFileDes(object):
    def __init__(self):
        self.merge_annot = [
            [".", "", "注释结果目录"],
            ["allannot_class", "", "已知基因与新预测合并注释结果目录"],
            ["allannot_class/cog", "", "cog注释结果目录"],
            ["allannot_class/cog/cog_list_tran.xls", "", "cog注释详情表"],
            ["allannot_class/cog/cog_venn_gene.txt", "", "存在cog注释的基因列表"],
            ["allannot_class/cog/cog_venn_tran.txt", "", "存在cog注释的转录本列表"],
            ["allannot_class/go/", "", "go注释结果目录"],
            ["allannot_class/go/go_lev2_gene.stat.xls", "", "基因go二级分类统计表"],
            ["allannot_class/go/go_lev2_tran.stat.xls", "", "转录本go二级分类统计表"],
            ["allannot_class/go/go_lev3_gene.stat.xls", "", "基因go三级分类统计表"],
            ["allannot_class/go/go_lev3_tran.stat.xls", "", "转录本go三级分类统计表"],
            ["allannot_class/go/go_lev4_gene.stat.xls", "", "基因go四级分类统计表"],
            ["allannot_class/go/go_lev4_tran.stat.xls", "", "转录本go四级分类统计表"],
            ["allannot_class/go/go_list_gene.xls", "", "基因go注释列表"],
            ["allannot_class/go/go_list_tran.xls", "", "转录本go注释列表"],
            ["allannot_class/go/go_venn_gene.txt", "", "存在go注释的基因列表"],
            ["allannot_class/go/go_venn_tran.txt", "", "存在go注释的转录本列表"],
            ["allannot_class/kegg", "", "kegg注释结果目录"],
            ["allannot_class/kegg/kegg_gene_gene.xls", "", "基因kegg注释详情表"],
            ["allannot_class/kegg/kegg_gene_tran.xls", "", "转录本kegg注释详情表"],
            ["allannot_class/kegg/kegg_pathway_gene_dir:", "", "基因kegg注释通路图"],
            ["allannot_class/kegg/kegg_pathway_gene.xls", "", "基因kegg pathway注释详情表"],
            ["allannot_class/kegg/kegg_pathway_tran_dir:", "", "转录本kegg通路图"],
            ["allannot_class/kegg/kegg_pathway_tran.xls", "", "转录本kegg pathway注释详情表"],
            ["allannot_class/kegg/kegg_venn_gene.txt", "", "存在kegg注释的基因列表"],
            ["allannot_class/kegg/kegg_venn_tran.txt", "", "存在kegg注释的转录本列表"],
            ["allannot_class/nr", "", "nr注释结果目录"],
            ["allannot_class/nr/nr_blast_gene.xls", "", "基因nr注释详情表"],
            ["allannot_class/nr/nr_blast_tran.xls", "", "转录本nr注释详情表"],
            ["allannot_class/nr/nr_venn_gene.txt", "", "存在nr注释的基因列表"],
            ["allannot_class/nr/nr_venn_tran.txt", "", "存在nr注释的转录本列表"],
            ["allannot_class/pfam", "", "pfam注释结果目录"],
            ["allannot_class/pfam/pfam_domain_gene.xls", "", "基因pfam注释详情表"],
            ["allannot_class/pfam/pfam_domain_tran.xls", "", "转录本pfam注释详情表"],
            ["allannot_class/pfam/pfam_venn_gene.txt", "", "存在pfam注释的基因列表"],
            ["allannot_class/pfam/pfam_venn_tran.txt", "", "存在pfam注释的转录本列表"],
            ["allannot_class/swissprot", "", "swissprot注释结果目录"],
            ["allannot_class/swissprot/swissprot_blast_gene.xls", "", "基因swissprot注释详情表"],
            ["allannot_class/swissprot/swissprot_blast_tran.xls", "", "转录本swissprot注释详情表"],
            ["allannot_class/swissprot/swissprot_venn_gene.txt", "", "存在swissprot注释的基因列表"],
            ["allannot_class/swissprot/swissprot_venn_tran.txt", "", "存在swissprot注释的基因列表"],
            ["newannot_class", "", "新预测转录本注释结果目录"],
            ["newannot_class/cog", "", "cog注释结果目录"],
            ["newannot_class/cog/cog_list_tran.xls", "", "cog注释详情表"],
            ["newannot_class/cog/cog_venn_gene.txt", "", "存在cog注释的基因列表"],
            ["newannot_class/cog/cog_venn_tran.txt", "", "存在cog注释的转录本列表"],
            ["newannot_class/go/", "", "go注释结果目录"],
            ["newannot_class/go/go_lev2_gene.stat.xls", "", "基因go二级分类统计表"],
            ["newannot_class/go/go_lev2_tran.stat.xls", "", "转录本go二级分类统计表"],
            ["newannot_class/go/go_lev3_gene.stat.xls", "", "基因go三级分类统计表"],
            ["newannot_class/go/go_lev3_tran.stat.xls", "", "转录本go三级分类统计表"],
            ["newannot_class/go/go_lev4_gene.stat.xls", "", "基因go四级分类统计表"],
            ["newannot_class/go/go_lev4_tran.stat.xls", "", "转录本go四级分类统计表"],
            ["newannot_class/go/go_list_gene.xls", "", "基因go注释列表"],
            ["newannot_class/go/go_list_tran.xls", "", "转录本go注释列表"],
            ["newannot_class/go/go_venn_gene.txt", "", "存在go注释的基因列表"],
            ["newannot_class/go/go_venn_tran.txt", "", "存在go注释的转录本列表"],
            ["newannot_class/kegg", "", "kegg注释结果目录"],
            ["newannot_class/kegg/kegg_gene_gene.xls", "", "基因kegg注释详情表"],
            ["newannot_class/kegg/kegg_gene_tran.xls", "", "转录本kegg注释详情表"],
            ["newannot_class/kegg/kegg_pathway_gene_dir:", "", "基因kegg注释通路图"],
            ["newannot_class/kegg/kegg_pathway_gene.xls", "", "基因kegg pathway注释详情表"],
            ["newannot_class/kegg/kegg_pathway_tran_dir:", "", "转录本kegg通路图"],
            ["newannot_class/kegg/kegg_pathway_tran.xls", "", "转录本kegg pathway注释详情表"],
            ["newannot_class/kegg/kegg_venn_gene.txt", "", "存在kegg注释的基因列表"],
            ["newannot_class/kegg/kegg_venn_tran.txt", "", "存在kegg注释的转录本列表"],
            ["newannot_class/nr", "", "nr注释结果目录"],
            ["newannot_class/nr/nr_blast_gene.xls", "", "基因nr注释详情表"],
            ["newannot_class/nr/nr_blast_tran.xls", "", "转录本nr注释详情表"],
            ["newannot_class/nr/nr_venn_gene.txt", "", "存在nr注释的基因列表"],
            ["newannot_class/nr/nr_venn_tran.txt", "", "存在nr注释的转录本列表"],
            ["newannot_class/pfam", "", "pfam注释结果目录"],
            ["newannot_class/pfam/pfam_domain_gene.xls", "", "基因pfam注释详情表"],
            ["newannot_class/pfam/pfam_domain_tran.xls", "", "转录本pfam注释详情表"],
            ["newannot_class/pfam/pfam_venn_gene.txt", "", "存在pfam注释的基因列表"],
            ["newannot_class/pfam/pfam_venn_tran.txt", "", "存在pfam注释的转录本列表"],
            ["newannot_class/swissprot", "", "swissprot注释结果目录"],
            ["newannot_class/swissprot/swissprot_blast_gene.xls", "", "基因swissprot注释详情表"],
            ["newannot_class/swissprot/swissprot_blast_tran.xls", "", "转录本swissprot注释详情表"],
            ["newannot_class/swissprot/swissprot_venn_gene.txt", "", "存在swissprot注释的基因列表"],
            ["newannot_class/swissprot/swissprot_venn_tran.txt", "", "存在swissprot注释的基因列表"],
            ["refannot_class", "", "已知基因/转录本注释结果目录"],
            ["refannot_class/cog", "", "cog注释结果目录"],
            ["refannot_class/cog/cog_list_tran.xls", "", "cog注释详情表"],
            ["refannot_class/cog/cog_venn_gene.txt", "", "存在cog注释的基因列表"],
            ["refannot_class/cog/cog_venn_tran.txt", "", "存在cog注释的转录本列表"],
            ["refannot_class/go/", "", "go注释结果目录"],
            ["refannot_class/go/go_lev2_gene.stat.xls", "", "基因go二级分类统计表"],
            ["refannot_class/go/go_lev2_tran.stat.xls", "", "转录本go二级分类统计表"],
            ["refannot_class/go/go_lev3_gene.stat.xls", "", "基因go三级分类统计表"],
            ["refannot_class/go/go_lev3_tran.stat.xls", "", "转录本go三级分类统计表"],
            ["refannot_class/go/go_lev4_gene.stat.xls", "", "基因go四级分类统计表"],
            ["refannot_class/go/go_lev4_tran.stat.xls", "", "转录本go四级分类统计表"],
            ["refannot_class/go/go_list_gene.xls", "", "基因go注释列表"],
            ["refannot_class/go/go_list_tran.xls", "", "转录本go注释列表"],
            ["refannot_class/go/go_venn_gene.txt", "", "存在go注释的基因列表"],
            ["refannot_class/go/go_venn_tran.txt", "", "存在go注释的转录本列表"],
            ["refannot_class/kegg", "", "kegg注释结果目录"],
            ["refannot_class/kegg/kegg_gene_gene.xls", "", "基因kegg注释详情表"],
            ["refannot_class/kegg/kegg_gene_tran.xls", "", "转录本kegg注释详情表"],
            ["refannot_class/kegg/kegg_pathway_gene_dir:", "", "基因kegg注释通路图"],
            ["refannot_class/kegg/kegg_pathway_gene.xls", "", "基因kegg pathway注释详情表"],
            ["refannot_class/kegg/kegg_pathway_tran_dir:", "", "转录本kegg通路图"],
            ["refannot_class/kegg/kegg_pathway_tran.xls", "", "转录本kegg pathway注释详情表"],
            ["refannot_class/kegg/kegg_venn_gene.txt", "", "存在kegg注释的基因列表"],
            ["refannot_class/kegg/kegg_venn_tran.txt", "", "存在kegg注释的转录本列表"],
            ["refannot_class/nr", "", "nr注释结果目录"],
            ["refannot_class/nr/nr_blast_gene.xls", "", "基因nr注释详情表"],
            ["refannot_class/nr/nr_blast_tran.xls", "", "转录本nr注释详情表"],
            ["refannot_class/nr/nr_venn_gene.txt", "", "存在nr注释的基因列表"],
            ["refannot_class/nr/nr_venn_tran.txt", "", "存在nr注释的转录本列表"],
            ["refannot_class/pfam", "", "pfam注释结果目录"],
            ["refannot_class/pfam/pfam_domain_gene.xls", "", "基因pfam注释详情表"],
            ["refannot_class/pfam/pfam_domain_tran.xls", "", "转录本pfam注释详情表"],
            ["refannot_class/pfam/pfam_venn_gene.txt", "", "存在pfam注释的基因列表"],
            ["refannot_class/pfam/pfam_venn_tran.txt", "", "存在pfam注释的转录本列表"],
            ["refannot_class/swissprot", "", "swissprot注释结果目录"],
            ["refannot_class/swissprot/swissprot_blast_gene.xls", "", "基因swissprot注释详情表"],
            ["refannot_class/swissprot/swissprot_blast_tran.xls", "", "转录本swissprot注释详情表"],
            ["refannot_class/swissprot/swissprot_venn_gene.txt", "", "存在swissprot注释的基因列表"],
            ["refannot_class/swissprot/swissprot_venn_tran.txt", "", "存在swissprot注释的基因列表"],
            ["newannot_mapdb/eggnog", "", "新转录本eggnog数据库比对结果目录"],
            ["newannot_mapdb/GO", "", "新转录本GO数据库比对结果目录"],
            ["newannot_mapdb/kegg", "", "新转录本kegg数据库比对结果目录"],
            ["newannot_mapdb/nr", "", "新转录本nr数据库比对结果目录"],
            ["newannot_mapdb/swissprot", "", "新转录本swissprot数据库比对结果目录"],
        ]

