# -*- coding: utf-8 -*-
# __author__ = 'qinjincheng'

from optparse import OptionParser
import fileinput

parser = OptionParser(description='Add class code to each line of GTF file generated by gffcompare')
parser.add_option('-i', '--input', dest='input', help='Input GTF file generated by gffcompare')
parser.add_option('-t', '--tmap', dest='tmap', help='Input TMAP file generated by gffcompare')
parser.add_option('-o', '--output', dest='output', help='Output modified GTF file')
(opts, args) = parser.parse_args()

def main(file_in, tmap, file_out):
    def get_info_dic_from_tmap(srcfile):
        dct = dict()
        for line in fileinput.input(srcfile):
            arr = line.strip().split('\t')
            qry_id = arr[4]
            class_code = arr[2]
            dct[qry_id] = class_code
        return dct
    dct = get_info_dic_from_tmap(tmap)
    with open(file_out, 'w') as fw:
        for line in fileinput.input(file_in):
            if line[0] != '#':
                arr = line.strip().split('\t')
                if len(arr) >= 9:
                    attributes = arr[8]
                    for attribute in attributes.split(';'):
                        if 'transcript_id' in attribute:
                            transcript_id = attribute.split('"')[1]
                            if dct.has_key(transcript_id):
                                fw.write('{} class_code "{}";\n'.format(line.strip(), dct[transcript_id]))
                                break

if __name__ == '__main__':
    if opts.input and opts.tmap and opts.output:
        main(opts.input, opts.tmap, opts.output)
    else:
        parser.print_help()